apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata: # kpt-merge: /example-multus
  name: regional-multus
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|PackageVariant|default|example-multus'
  labels:
    nephio.org/region: us-west1
    nephio.org/site-type: regional
spec:
  annotations:
    approval.nephio.org/policy: initial
    approval.nephio.org/delay: 2m
  upstream:
    package: multus
    repo: nephio-example-packages
    revision: v1
  downstream:
    package: regional-multus
    repo: mgmt-staging
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: regional
